version: '3.8'

services:

wordpress:
    image: wordpress:php7.2-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: aqui_su_password
      WORDPRESS_DB_NAME: db
    volumes:
      - ./public:/var/www/html
    links:
      - mysql:mysql

mysql:
    image: mysql:8.0.13
    restart: always
#    ports:
#      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: aqui_su_password
    volumes:
      - ./mysql-data:/var/lib/mysql
